### ISSUE TITLE
Files not downloading. No XML found when running `get_subxml_from_metadata`

### ISSUE THREAD

**Issue by pbrotoisworo** [forrestfwilliams/burst2safe#28]
Hello,

I've tried running burst2safe in Google Colab but it fails due to no XML file found. The content directory in Colab is empty.

I've just used the commands in the readme file to install it via pip. Then run a sample CLI command
`!burst2safe --orbit 32861 --bbox 53.57 27.54 53.78 27.60 --pols VV VH`

It fails in this particular line because no XML file is found:
https://github.com/forrestfwilliams/burst2safe/blob/b8cb864ebfdfe83733d6174b0be67d5aaae89784/src/burst2safe/utils.py#L192

Here are the print statements before it failed:
```
Using burst group search...
Found 4 burst(s).
Check burst group validity...
Downloading data...
Download complete.
Creating SAFE...
```

Here is the traceback:
```python
Traceback (most recent call last):
  File "/usr/local/bin/burst2safe", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/burst2safe.py", line 166, in main
    burst2safe(
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/burst2safe.py", line 139, in burst2safe
    [info.add_shape_info() for info in burst_infos]
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/burst2safe.py", line 139, in <listcomp>
    [info.add_shape_info() for info in burst_infos]
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/utils.py", line 41, in add_shape_info
    annotation = get_subxml_from_metadata(self.metadata_path, 'product', self.swath, self.polarization)
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/utils.py", line 192, in get_subxml_from_metadata
    with open(metadata_path, 'r') as metadata_file:
FileNotFoundError: [Errno 2] No such file or directory: '/content/S1A_IW_SLC__1SDV_20200604T022251_20200604T022318_032861_03CE65_7C85_VV.xml'
```

**Comment by forrestfwilliams** [comment]
Hey @pbrotoisworo thank you for the issue. Turns out I was run into a race condition when using a `ThreadPoolExecutor` with `asf_search.download_url` that resulted in downloads intermittently being skipped. I've open PR #29 to fix the issue.

**Comment by forrestfwilliams** [comment]
Ah, yes. You will need to set up an EarthData login account and update your `~/.netrc` file to download data. You can sign up for an EarthData login account [here](https://urs.earthdata.nasa.gov/home), and here are instructions for [setting up your `~/.netrc`](https://harmony.earthdata.nasa.gov/docs#getting-started).
